mig:
  build: MIG
  ports: 
   - "51664:51664"
  links:
   - postgres
   - rabbitmq
  hostname: api.mig.example.com
postgres:
  build: postgres
  expose:
   - "5432"
rabbitmq:
  build: rabbitmq
  expose:
   - "5671"
  hostname: mig.example.com
resolvable:
  image: mgood/resolvable
  hostname: resolvable
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock 
    - /etc/resolv.conf:/tmp/resolv.conf
